import { useState, type FormEvent } from "react";
import type { OrderCreateInput, PublicOrder, PaymentMethod } from "../../shared/commerce-journeys";
import { orderLabels, paymentMethods } from "../../shared/commerce-journeys";
import type { PublicStorefront } from "./types";
import type { StoreCart } from "./cart";
import { cartLineKey } from "./cart";
import { apiBaseUrl } from "../admin/runtime";
import { timedFetch } from "../lib/requests";
import { useDraft } from "../lib/drafts";
import "./cart.css";

function secret(){return [...crypto.getRandomValues(new Uint8Array(32))].map(v=>v.toString(16).padStart(2,"0")).join("");}
export default function CartCheckout({storefront,cart,language}: {storefront:PublicStorefront;cart:StoreCart;language:"fr"|"en"}) {
  const fr=language==="fr",labels=orderLabels[language];const[name,setName]=useState("");const[phone,setPhone]=useState("");const[note,setNote]=useState("");const[method,setMethod]=useState<PaymentMethod>("cash");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[receipt,setReceipt]=useState<{order:PublicOrder;href:string;token:string}|null>(null);
  const draft=useDraft<OrderCreateInput|null>("commerce-order-attempt:"+storefront.store.slug,null,(v):v is OrderCreateInput|null=>v===null||Boolean(v&&typeof v==="object"&&"trackingToken" in v&&"idempotencyKey" in v&&"lines" in v));
  const pending=draft.value;
  const rows=(pending?.lines || cart.lines).map(line=>({line,product:storefront.products.find(p=>p.id===line.productId)}));
  const valid=rows.every(({line,product})=>product&&product.currencyCode===storefront.store.currencyCode&&Object.entries(line.variants).every(([name,value])=>product.variants.some(v=>v.name===name&&v.value===value))&&new Set(product.variants.map(v=>v.name)).size===Object.keys(line.variants).length);
  const total=rows.reduce((sum,{line,product})=>sum+line.quantity*Number(product?.price||0),0);
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");const input=pending || {idempotencyKey:crypto.randomUUID(),trackingToken:secret(),lines:cart.lines.map(l=>({...l,variants:{...l.variants}})),paymentMethod:method,customerName:name.trim()||null,customerPhone:phone.trim()||null,note:note.trim()||null};draft.setValue(input);
    try{const response=await timedFetch(apiBaseUrl+"/v1/public/stores/"+encodeURIComponent(storefront.store.slug)+"/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...input,language})});if(!response.ok){const body=await response.json();if(body.error==="CATALOG_CHANGED"){draft.setValue(null);throw new Error("CATALOG_CHANGED");}throw new Error("REQUEST_FAILED");}const result=await response.json() as {order:PublicOrder;href:string};if(!result.href.startsWith("https://wa.me/"))throw new Error("INVALID_DESTINATION");cart.complete(input.idempotencyKey,input.lines);draft.setValue(null);draft.discard();setReceipt({...result,token:input.trackingToken});}
    catch(e){setError(e instanceof Error&&e.message==="CATALOG_CHANGED" ? (fr ? "Un prix, produit ou une variante a changé. Actualisez le catalogue avant de confirmer à nouveau." : "A price, product or variant changed. Refresh the catalog before confirming again.") : (fr ? "La connexion a été interrompue. Réessayez cette même demande : elle ne sera pas créée deux fois." : "The connection was interrupted. Retry the same request: it will not create a duplicate."));}finally{setBusy(false);}
  }
  if(receipt){const href="/orders/"+receipt.order.id+"#token="+receipt.token;return <section className="cart-content"><span className="public-overline">{storefront.store.name}</span><h1>{fr ? "Votre demande est enregistrée" : "Your request is saved"}</h1><div className="cart-receipt info-card"><strong>{receipt.order.reference}</strong><p>{fr ? "Elle attend la confirmation du vendeur. Convenez sur WhatsApp de la disponibilité, du paiement et de la remise." : "It awaits seller confirmation. Agree availability, payment and handover on WhatsApp."}</p><a className="cart-primary" href={receipt.href}>{fr ? "Ouvrir WhatsApp avec ma demande" : "Open WhatsApp with my request"}</a><a className="cart-secondary" href={href}>{fr ? "Suivre ma commande" : "Track my order"}</a><p>{fr ? "Conservez ce lien privé de suivi." : "Keep this private tracking link."}</p><input aria-label={fr ? "Lien privé de suivi" : "Private tracking link"} value={window.location.origin+href} readOnly onFocus={e=>e.target.select()} /></div><a href={"/store/"+storefront.store.slug}>{fr ? "Retour à la boutique" : "Back to store"}</a></section>;}
  return <section className="cart-content"><span className="public-overline">{storefront.store.name}</span><h1>{fr ? "Votre panier" : "Your cart"}</h1><p>{fr ? "Enregistrez votre demande puis échangez avec le vendeur sur WhatsApp." : "Save your request, then talk to the seller on WhatsApp."}</p>{!cart.available&&<p role="status">{fr ? "Le stockage n’est pas disponible sur cet appareil. Gardez cette page ouverte." : "Storage is unavailable on this device. Keep this page open."}</p>}
    {pending&&<p className="draft-note" role="status">{fr ? "Une demande attend une confirmation réseau. Réessayez-la avant de modifier ce panier." : "A request is awaiting network confirmation. Retry it before changing this cart."}</p>}
    {cart.lines.length===0&&!pending ? <div className="info-card"><h2>{fr ? "Le panier attend vos découvertes" : "Your cart is ready for discoveries"}</h2><a href={"/store/"+storefront.store.slug}>{fr ? "Parcourir les produits" : "Browse products"}</a></div> : <><div className="cart-checkout-grid"><div className="cart-lines">{rows.map(({line,product})=><article className="cart-line" key={cartLineKey(line)}>{product?.imageUrls[0]&&<img src={product.imageUrls[0]} alt="" width="96" height="96" />}<div><h2>{product ? product.name : (fr ? "Produit indisponible" : "Unavailable product")}</h2><p>{Object.entries(line.variants).map(([name,value])=>name+": "+value).join(" · ")}</p>{product&&<strong>{Number(product.price).toLocaleString(fr ? "fr-FR" : "en-GB")} {product.currencyCode}</strong>}<label>{fr ? "Quantité" : "Quantity"}<select value={line.quantity} disabled={Boolean(pending)||busy} onChange={e=>cart.quantity(line,Number(e.target.value))} aria-label={(fr ? "Quantité de " : "Quantity for ")+(product?.name||line.productId)}>{Array.from({length:99},(_,i)=><option value={i+1} key={i+1}>{i+1}</option>)}</select></label><button type="button" className="cart-text-button" disabled={Boolean(pending)||busy} onClick={()=>cart.remove(line)}>{fr ? "Retirer" : "Remove"}</button></div></article>)}</div>
    <form className="cart-form info-card" onSubmit={submit} aria-busy={busy}><h2>{fr ? "Votre demande" : "Your request"}</h2>{!pending && <p className="cart-total">{total.toLocaleString(fr ? "fr-FR" : "en-GB")} {storefront.store.currencyCode}</p>}<p>{fr ? "Ce montant est revérifié avant l’enregistrement. Aucun paiement n’est effectué ici ; le stock et la remise restent à confirmer." : "The amount is rechecked before saving. No payment is made here; stock and handover must be confirmed."}</p>
      {!pending&&<><label>{fr ? "Votre nom (facultatif)" : "Your name (optional)"}<input value={name} onChange={e=>setName(e.target.value)} autoComplete="name" maxLength={80} /></label><label>{fr ? "Téléphone (facultatif)" : "Phone (optional)"}<input value={phone} onChange={e=>setPhone(e.target.value)} autoComplete="tel" inputMode="tel" maxLength={24} pattern="\+?[0-9 ()-]{8,24}" /></label><label>{fr ? "Note au vendeur (facultative)" : "Note to seller (optional)"}<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={500} rows={3} /></label><label>{fr ? "Paiement à convenir avec le vendeur" : "Payment to agree with seller"}<select value={method} onChange={e=>setMethod(e.target.value as PaymentMethod)}>{paymentMethods.map(value=><option value={value} key={value}>{labels[value]}</option>)}</select></label><label className="consent-row"><input type="checkbox" required /><span>{fr ? "J’ai lu les conditions. Cette demande attend la confirmation du vendeur." : "I have read the terms. This request awaits seller confirmation."} <a href="/terms" target="_blank" rel="noreferrer">{fr ? "Conditions" : "Terms"}</a> · <a href="/privacy" target="_blank" rel="noreferrer">{fr ? "Confidentialité" : "Privacy"}</a></span></label></>}
      {!valid&&!pending&&<p role="alert" className="public-handoff-error">{fr ? "Un produit ou une variante est indisponible. Retirez-le et choisissez à nouveau dans la boutique." : "A product or variant is unavailable. Remove it and choose again in the store."}</p>}{error&&<p role="alert" className="public-handoff-error">{error}</p>}
      <button type="submit" className="cart-primary" disabled={busy || (!pending&&(!valid||!cart.lines.length))}>{busy ? (fr ? "Enregistrement…" : "Saving…") : pending ? (fr ? "Réessayer la même demande" : "Retry the same request") : (fr ? "Enregistrer ma demande" : "Save my request")}</button>{error&&<a href={window.location.pathname}>{fr ? "Actualiser le catalogue" : "Refresh catalog"}</a>}
    </form></div></>}
    <a className="cart-back" href={"/store/"+storefront.store.slug}>← {fr ? "Continuer mes achats" : "Continue shopping"}</a>
  </section>;
}
