import { useEffect, useState, type FormEvent } from "react";
import { merchantRequest } from "./api";
import type { CommerceAuthClient } from "./auth";
import type { PlatformStore, SupportStatus, SupportTicket } from "../../shared/commerce-journeys";

export default function PlatformPanel({client,language}: {client:CommerceAuthClient;language:"fr"|"en"}) {
  const fr=language==="fr";const[stores,setStores]=useState<PlatformStore[]>([]);const[tickets,setTickets]=useState<SupportTicket[]>([]);const[query,setQuery]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");
  async function load(event?:FormEvent){event?.preventDefault();setBusy(true);setError("");try{const result=await Promise.all([merchantRequest<{stores:PlatformStore[]}>(client,"/v1/admin/platform/stores?q="+encodeURIComponent(query)),merchantRequest<{tickets:SupportTicket[]}>(client,"/v1/admin/platform/support")]);setStores(result[0].stores);setTickets(result[1].tickets);}catch{setError(fr ? "Console inaccessible. Un accès support Trigenys explicite est nécessaire ; sinon, réessayez." : "Console unavailable. Explicit Trigenys support access is required; otherwise, try again.");}finally{setBusy(false);}}
  useEffect(()=>{void load();},[]);
  async function reply(event:FormEvent<HTMLFormElement>,ticket:SupportTicket){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setError("");try{const result=await merchantRequest<{ticket:SupportTicket}>(client,"/v1/admin/platform/support/"+ticket.id,{method:"PATCH",body:JSON.stringify({status:form.get("status"),reply:form.get("reply")})});setTickets(current=>current.map(t=>t.id===ticket.id ? result.ticket:t));setMessage(fr ? "Réponse enregistrée et disponible dans le suivi privé." : "Reply saved and available in private tracking.");}catch{setError(fr ? "La réponse n’a pas été enregistrée. Réessayez." : "The reply was not saved. Try again.");}finally{setBusy(false);}}
  const statuses:SupportStatus[]=["open","in_progress","resolved"];
  return <section className="workspace-section"><span className="admin-eyebrow">Trigenys</span><h1>{fr ? "Support de la plateforme" : "Platform support"}</h1><p>{fr ? "Demandes d’aide et métadonnées des boutiques. Les commandes et coordonnées acheteur restent dans l’espace marchand." : "Support requests and store metadata. Orders and buyer contact details stay in the merchant workspace."}</p>
    {busy && <p role="status">{fr ? "Chargement…" : "Loading…"}</p>}{error && <p className="form-message error" role="alert">{error}</p>}{message && <p role="status">{message}</p>}
    <form className="workspace-search" onSubmit={load}><label>{fr ? "Rechercher une boutique" : "Find a store"}<input value={query} onChange={e=>setQuery(e.target.value)} maxLength={80} type="search" /></label><button className="admin-secondary" type="submit" disabled={busy}>{fr ? "Rechercher / actualiser" : "Search / refresh"}</button></form>
    <h2>{fr ? "Boutiques" : "Stores"}</h2><ul className="team-list">{stores.map(store=><li className="info-card" key={store.id}><strong>{store.name}</strong><span>{store.slug} · {store.status} · {store.productCount} {fr ? "produits" : "products"}</span>{store.status==="published" && <a href={"/store/"+store.slug}>{fr ? "Voir le catalogue public" : "View public catalog"}</a>}</li>)}</ul>
    <h2>{fr ? "Demandes d’aide" : "Support requests"}</h2>{!busy&&!error&&tickets.length===0&&<p>{fr ? "Aucune demande pour le moment." : "No requests yet."}</p>}
    <div className="orders-list">{tickets.map(ticket=><details className="info-card" key={ticket.id}><summary>{ticket.name} · {ticket.status==="open" ? (fr ? "Reçue" : "Received") : ticket.status==="in_progress" ? (fr ? "En cours" : "In progress") : (fr ? "Traitée" : "Resolved")}</summary><p>{ticket.email}</p><p className="preserve-lines">{ticket.message}</p><form className="admin-form" onSubmit={e=>reply(e,ticket)}><label><span>{fr ? "Statut" : "Status"}</span><select aria-label={fr ? "Statut" : "Status"} name="status" defaultValue={ticket.status}>{statuses.map(status=><option value={status} key={status}>{status==="open" ? (fr ? "Reçue" : "Received") : status==="in_progress" ? (fr ? "En cours" : "In progress") : (fr ? "Traitée" : "Resolved")}</option>)}</select></label><label><span>{fr ? "Réponse visible dans le suivi privé" : "Reply visible in private tracking"}</span><textarea name="reply" defaultValue={ticket.reply || ""} rows={4} maxLength={4000} /></label><button type="submit" className="admin-primary" disabled={busy}>{fr ? "Enregistrer la réponse" : "Save reply"}</button></form></details>)}</div>
  </section>;
}
