import { useEffect, useState, type FormEvent } from "react";
import { merchantRequest, type Store } from "./api";
import type { CommerceAuthClient } from "./auth";
import type { Invitation, StoreMember } from "../../shared/commerce-journeys";

export default function TeamPanel({client,store,language}: {client:CommerceAuthClient;store:Store;language:"fr"|"en"}) {
  const fr=language==="fr";const[team,setTeam]=useState<{members:StoreMember[];invitations:Invitation[]}>({members:[],invitations:[]});const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[email,setEmail]=useState("");const[href,setHref]=useState("");const[message,setMessage]=useState("");const path="/v1/admin/stores/"+store.id+"/team";
  async function load(){setBusy(true);setError("");try{setTeam(await merchantRequest(client,path));}catch{setError(fr ? "L’équipe est inaccessible. Réessayez ou demandez l’accès au propriétaire." : "Team access is unavailable. Retry or ask the owner.");}finally{setBusy(false);}}
  useEffect(()=>{void load();},[store.id]);
  async function invite(event:FormEvent){event.preventDefault();setBusy(true);setError("");setHref("");try{const result=await merchantRequest<{href:string}>(client,path+"/invitations",{method:"POST",body:JSON.stringify({email})});setHref(result.href);setEmail("");await load();}catch{setError(fr ? "L’invitation n’a pas pu être créée. Réessayez." : "The invitation could not be created. Try again.");}finally{setBusy(false);}}
  async function revoke(kind:"members"|"invitations",id:string){if(!window.confirm(fr ? "Retirer cet accès ? La personne ne pourra plus utiliser cette invitation ou cette boutique." : "Remove this access? This person will no longer be able to use the invitation or this store."))return;setBusy(true);setError("");try{await merchantRequest(client,path+"/"+kind+"/"+id,{method:"DELETE"});setHref("");await load();setMessage(fr ? "Accès retiré." : "Access removed.");}catch{setError(fr ? "L’accès n’a pas pu être retiré. Réessayez." : "Access could not be removed. Try again.");}finally{setBusy(false);}}
  if(store.role==="staff")return <section className="workspace-section"><h1>{fr ? "Accès réservé au propriétaire" : "Owner access required"}</h1><p>{fr ? "Vous pouvez gérer les produits et les commandes de cette boutique." : "You can manage this store’s products and orders."}</p></section>;
  return <section className="workspace-section"><h1>{fr ? "Votre équipe" : "Your team"}</h1><p>{fr ? "Un collaborateur gère le catalogue et les commandes. Les réglages, paiements, statistiques et invitations restent au propriétaire." : "Staff manage the catalog and orders. Settings, payments, analytics and invitations remain with the owner."}</p>
    {busy && <p role="status">{fr ? "Opération en cours…" : "Working…"}</p>}{error && <p className="form-message error" role="alert">{error}</p>}{message && <p role="status">{message}</p>}
    <form className="admin-form info-card" onSubmit={invite}><h2>{fr ? "Inviter un collaborateur" : "Invite a staff member"}</h2><label><span>{fr ? "Email de la personne" : "Recipient email"}</span><input type="email" autoComplete="off" value={email} onChange={e=>setEmail(e.target.value)} maxLength={254} required /></label><p>{fr ? "Le lien est valable 48 heures, utilisable une fois et lié à cet email vérifié. Partagez-le directement avec la personne. Aucun email n’est envoyé automatiquement." : "The link is valid for 48 hours, single-use and bound to this verified email. Share it directly with the recipient. No automatic email is sent."}</p><button className="admin-primary" type="submit" disabled={busy}>{fr ? "Créer l’invitation" : "Create invitation"}</button></form>
    {href && <div className="info-card"><h2>{fr ? "Lien privé à partager" : "Private link to share"}</h2><label className="admin-form"><span>{fr ? "Invitation" : "Invitation"}</span><input readOnly value={href} onFocus={e=>e.target.select()} /></label><button type="button" className="admin-secondary" onClick={async()=>{try{await navigator.clipboard.writeText(href);setMessage(fr ? "Lien copié." : "Link copied.");}catch{setMessage(fr ? "Sélectionnez et copiez le lien ci-dessus." : "Select and copy the link above.");}}}>{fr ? "Copier le lien" : "Copy link"}</button></div>}
    <h2>{fr ? "Membres" : "Members"}</h2><ul className="team-list">{team.members.map((member,i)=><li className="info-card" key={member.id}><strong>{member.role==="owner" ? (fr ? "Propriétaire" : "Owner") : (member.email || (fr ? "Collaborateur "+(i+1) : "Staff member "+(i+1)))}</strong>{member.role==="staff" && <button className="admin-secondary" type="button" disabled={busy} onClick={()=>revoke("members",member.id)}>{fr ? "Retirer l’accès" : "Remove access"}</button>}</li>)}</ul>
    <h2>{fr ? "Invitations" : "Invitations"}</h2><ul className="team-list">{team.invitations.map(inv=><li className="info-card" key={inv.id}><strong>{inv.email}</strong><span>{inv.acceptedAt ? (fr ? "Acceptée" : "Accepted") : inv.revokedAt ? (fr ? "Retirée" : "Revoked") : new Date(inv.expiresAt).getTime()<Date.now() ? (fr ? "Expirée" : "Expired") : (fr ? "En attente" : "Pending")}</span>{!inv.acceptedAt&&!inv.revokedAt&&new Date(inv.expiresAt).getTime()>Date.now() && <button className="admin-secondary" type="button" disabled={busy} onClick={()=>revoke("invitations",inv.id)}>{fr ? "Annuler l’invitation" : "Revoke invitation"}</button>}</li>)}</ul>
    <button type="button" className="admin-secondary" disabled={busy} onClick={load}>{fr ? "Actualiser" : "Refresh"}</button>
  </section>;
}
